env:
  browser: true
  es2021: true
extends:
  - google
  - prettier
ignorePatterns:
  - "**/reports/**"
  - "**/assets/builds/**"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  quotes:
    - error
    - double
  max-len:
    - error
    - 100
  spaced-comment:
    - error
    - always
    - markers:
      - "="
  require-jsdoc: off
