detectors:
  Attribute:
    exclude:
      - "User#login"
  BooleanParameter:
    exclude:
      - "Nav::NavDropdownComponent#initialize"
  InstanceVariableAssumption:
    exclude:
      - "RejectBlankNestedAttributesForMatcher"
      - "User"
  IrresponsibleModule:
    enabled: false
  NilCheck:
    exclude:
      - "User#self.find_first_by_auth_conditions"
  TooManyStatements:
    enabled: false
  UtilityFunction:
    exclude:
      - "RejectBlankNestedAttributesForMatcher#reject_blank_nested_attributes_for"

directories:
  "app/components/**":
    FeatureEnvy:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/helpers/**":
    UtilityFunction:
      enabled: false
  "app/jobs/**":
    UtilityFunction:
      enabled: false
  "app/policies/**":
    InstanceVariableAssumption:
      enabled: false
  "db/**":
    UtilityFunction:
      enabled: false
  "db/migrate/**":
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    UtilityFunction:
      enabled: false
  "spec/support/**":
    UtilityFunction:
      enabled: false
