detectors:
  Attribute:
    exclude:
      - "User#login"
  InstanceVariableAssumption:
    exclude:
      - "User"
  IrresponsibleModule:
    enabled: false
  NilCheck:
    exclude:
      - "User#self.find_first_by_auth_conditions"

directories:
  "app/policies/**":
    InstanceVariableAssumption:
      enabled: false
  "db/migrate/**":
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    UtilityFunction:
      enabled: false
