extends:
  - "stylelint-config-standard-scss"

ignoreFiles:
  - "**/reports/**"
  - "**/assets/builds/**"

rules:
  no-descending-specificity: null
  selector-id-pattern: null
  scss/no-global-function-names: null
