services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
  - type: redis
    name: redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction
  # - type: worker
  #   name: sidekiq
  #   plan: starter
  #   env: ruby
  #   buildCommand: bundle install
  #   startCommand: bundle exec sidekiq
  #   envVars:
  #     - key: RAILS_MASTER_KEY
  #       sync: false
  #     - key: REDIS_URL
  #       fromService:
  #         type: redis
  #         name: redis
  #         property: connectionString

databases:
  - name: postgres
    plan: free
    ipAllowList: []
